### ISSUE TITLE
Question about VLM-Guided Scoring 

### ISSUE THREAD

**Issue by Jay-D13** [jmwang0117/HE-Drive#10]
Hi @jmwang0117,

Thank you for sharing your work on HE-Drive; it’s very impressive! I noticed that the code repository currently doesn’t include the VLM-guided scoring section, specifically the component where Llama 3.2V is used to dynamically adjust scoring weights based on scene context (e.g., adapting to “aggressive” or “conservative” driving styles).

From reading the paper, I understand that this module uses a Vision-Question-Answering (VQA) approach with multi-round dialogues to adjust scoring weights dynamically. I’d like to ask:

1. Will the VLM adjustments be added as an interactive or periodic update feature within the rule-based scoring framework?
2. Could you share any insights on integrating Llama 3.2V with the rule-based scorer, particularly to balance interpretability with adaptivity in different driving scenarios?

Looking forward to any updates you can share on this feature :)

**Comment by jmwang0117** [comment]
Thank you for your question, we will enrich the description of this part in the future version of the manuscript!
Here is a brief description:

Our VLM-guided scorer employs a parallel architecture comprising two main components: a rule-based scorer and a VLM-based scorer. This dual approach aims to leverage the strengths of both interpretable heuristics and advanced language model capabilities.

## Rule-Based Scorer

The rule-based component provides an initial, interpretable evaluation of the predicted trajectory. It utilizes predefined weights for various trajectory attributes, offering a transparent baseline for scoring.

## VLM-Based Scorer

The VLM-based scorer utilizes Llama 3.2V 11B and operates in two stages:

### Stage 1: Multi-Round Dialogue

In this stage, we prompt Llama 3.2V with a template containing:
- An image of the driving scenario
- Predefined aggressive and conservative driving styles
- Corresponding weight intervals for each style

This approach focuses the model's knowledge domain on driving style assessment and adjustment.

### Stage 2: Weight Adjustment

Llama 3.2V generates adjustment scores for each weight item in the rule-based scorer. These adjustments are directly applied to the corresponding rule-based weights. For example:

- Initial rule-based speed weight: 2.5
- VLM assessment: Level II aggressive
- VLM-proposed adjustment: +1.0
- Final speed weight: 3.5

## Scoring Framework

The scoring system categorizes driving styles into aggressive and conservative, each with three levels of intensity:

| Style       | Level | Weight Range |
|-------------|-------|--------------|
| Aggressive  | I     | 1.5 - 3.0    |
|             | II    | 1.0 - 1.4    |
|             | III   | 0.1 - 0.9    |
| Conservative| I     | 1.5 - 3.0    |
|             | II    | 1.0 - 1.4    |
|             | III   | 0.1 - 0.9    |

- Aggressive style penalizes slow trajectories
- Conservative style penalizes fast trajectories
- 
VLM scores are updated regularly through sampling of benchmark datasets (e.g., NuScenes) to ensure ongoing refinement and adaptability of the scoring system.
