### ISSUE TITLE
What's the meaning of the trajectory in the code? Thanks

### ISSUE THREAD

**Issue by FDInSky** [jmwang0117/HE-Drive#2]
https://github.com/jmwang0117/HE-Drive/blob/main/diffusion_head/train.py#L40

**Comment by jmwang0117** [comment]
Our diffusion motion planner leverages the principles of diffusion models to generate optimized trajectories. In the forward process, the planner introduces noise to the GT trajectory, while in the reverse process, it systematically denoises it. Through this iterative procedure, the network progressively learns to predict the noise, thereby optimizing trajectory generation.

A distinctive feature of our approach is the integration of 3D scene representation, historical prediction trajectory into the Denoising Diffusion Probabilistic Model (DDPM) as condition.  The 3D scene representation obtained by sparse perception covers the map information and other agent information in the current environment. Therefore,  the generated trajectories not only account for spatial constraints but also comply with safety requirements and motion guarantees.

To gain a comprehensive understanding of this technique, we recommend reviewing two seminal papers:
1. "Diffusion Policy: Visuomotor Policy Learning via Action Diffusion"
2. "3D Diffusion Policy"
