### ISSUE TITLE
Question about OpenScene implementation

### ISSUE THREAD

**Issue by RexGPT** [jmwang0117/HE-Drive#4]
Hi @jmwang0117 Thanks for the great work! I have some questions about the work. 
- Did you implement SparseDrive on OpenScene? And you just train it in multi stages or just  in one stage? 
- If you are based on SparseDrive, why the speed on nuscenes is 2 times faster, which is very weird.
- Can you share more details about training on OpenScene. About training epochs and data preparation.

**Comment by jmwang0117** [comment]
Thank you for your interest in our work. I'm pleased to provide more details about our implementation and methodology:

1. We implemented HE-Drive on the NAVSIM framework, which is built upon the OpenScene dataset and offers an enhanced closed-loop implementation. For those looking to incorporate OpenScene into their own projects, we recommend referring directly to NAVSIM. In our approach, we trained the second stage of SparseDrive to acquire 3D representations.

2. Regarding the inference speed improvements, our enhancements stem from both Sparse Perception and the motion planner. Notably, we utilize DDIM during inference, which contributes significantly to speed gains. This aspect is elaborated on page 14 of our manuscript.

3. For dataset integration, we suggest consulting the NAVSIM framework documentation. Our training process consisted of 10 epochs for the second stage of SparseDrive, followed by 50 epochs of joint training for perception and planning components.
