### ISSUE TITLE
Question about the anchor in the forward process

### ISSUE THREAD

**Issue by Reeki67** [jmwang0117/HE-Drive#5]
Hello!
  Thanks for your great job.  I have a question about the anchors. The input A0 of the forward process is also in the dimension of [B, Na, Ti, P]. But there is only one expert trajectory, so how are the Na anchors selected? Where do the other trajectories in the anchors come from?

**Comment by Gear420** [comment]
Thank you very much for your interest in our work!
During training:the Na anchors are noisy trajectories, generated by add random noise to the single expert trajectory to create multiple anchors, and the loss is computed using DDPM. 
During testing:the Na anchors are randomly generated noise, and the denoised trajectories are obtained through inference.
