### ISSUE TITLE
Question about the Target 

### ISSUE THREAD

**Issue by reverse-2020** [jmwang0117/HE-Drive#8]
Hello!
Thanks for your great job. 
I already know that in the training step, the target is the last point in the expert trajectory, and when in the inference step, there's no expert trajectory, so what's the target come from ? After all, scoring strategy based on it

**Comment by jmwang0117** [comment]
Thank you for your question. Our VLM-guided scorer is designed with a **_plug-and-play_** architecture, offering flexibility in its operation. When certain factors, such as the target point, are not present in the dataset, the corresponding scoring term is simply omitted from the calculation. It's important to note that our scoring strategies are not exclusively dependent on target location. This adaptive approach allows our system to maintain robustness across various scenarios. We appreciate your insight and will provide a more comprehensive explanation of this aspect in future iterations of our manuscript.
